/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.core

import io.circe.generic.AutoDerivation
import io.circe.{Decoder, Encoder}
import ru.restomatik.client.model._
import sttp.client3.circe.SttpCirceApi

object JsonSupport extends SttpCirceApi with AutoDerivation with DateSerializers with AdditionalTypeSerializers {

  implicit val ActionOnValidationRejectionDecoder: Decoder[ActionOnValidationRejection.ActionOnValidationRejection] = Decoder.decodeEnumeration(ActionOnValidationRejection)
  implicit val ActionOnValidationRejectionEncoder: Encoder[ActionOnValidationRejection.ActionOnValidationRejection] = Encoder.encodeEnumeration(ActionOnValidationRejection)
  implicit val AddressFormatTypeDecoder: Decoder[AddressFormatType.AddressFormatType] = Decoder.decodeEnumeration(AddressFormatType)
  implicit val AddressFormatTypeEncoder: Encoder[AddressFormatType.AddressFormatType] = Encoder.encodeEnumeration(AddressFormatType)
  implicit val AddressHintsServiceTypeDecoder: Decoder[AddressHintsServiceType.AddressHintsServiceType] = Decoder.decodeEnumeration(AddressHintsServiceType)
  implicit val AddressHintsServiceTypeEncoder: Encoder[AddressHintsServiceType.AddressHintsServiceType] = Encoder.encodeEnumeration(AddressHintsServiceType)
  implicit val ComboPriceModificationTypeDecoder: Decoder[ComboPriceModificationType.ComboPriceModificationType] = Decoder.decodeEnumeration(ComboPriceModificationType)
  implicit val ComboPriceModificationTypeEncoder: Encoder[ComboPriceModificationType.ComboPriceModificationType] = Encoder.encodeEnumeration(ComboPriceModificationType)
  implicit val CreationStatusDecoder: Decoder[CreationStatus.CreationStatus] = Decoder.decodeEnumeration(CreationStatus)
  implicit val CreationStatusEncoder: Encoder[CreationStatus.CreationStatus] = Encoder.encodeEnumeration(CreationStatus)
  implicit val DeliveryGeocodeServiceTypeDecoder: Decoder[DeliveryGeocodeServiceType.DeliveryGeocodeServiceType] = Decoder.decodeEnumeration(DeliveryGeocodeServiceType)
  implicit val DeliveryGeocodeServiceTypeEncoder: Encoder[DeliveryGeocodeServiceType.DeliveryGeocodeServiceType] = Encoder.encodeEnumeration(DeliveryGeocodeServiceType)
  implicit val DeliveryRestrictionRejectCodeDecoder: Decoder[DeliveryRestrictionRejectCode.DeliveryRestrictionRejectCode] = Decoder.decodeEnumeration(DeliveryRestrictionRejectCode)
  implicit val DeliveryRestrictionRejectCodeEncoder: Encoder[DeliveryRestrictionRejectCode.DeliveryRestrictionRejectCode] = Encoder.encodeEnumeration(DeliveryRestrictionRejectCode)
  implicit val DeliveryRestrictionsModeDecoder: Decoder[DeliveryRestrictionsMode.DeliveryRestrictionsMode] = Decoder.decodeEnumeration(DeliveryRestrictionsMode)
  implicit val DeliveryRestrictionsModeEncoder: Encoder[DeliveryRestrictionsMode.DeliveryRestrictionsMode] = Encoder.encodeEnumeration(DeliveryRestrictionsMode)
  implicit val DeliverySettingsServiceTypeDecoder: Decoder[DeliverySettingsServiceType.DeliverySettingsServiceType] = Decoder.decodeEnumeration(DeliverySettingsServiceType)
  implicit val DeliverySettingsServiceTypeEncoder: Encoder[DeliverySettingsServiceType.DeliverySettingsServiceType] = Encoder.encodeEnumeration(DeliverySettingsServiceType)
  implicit val DeliveryStatusDecoder: Decoder[DeliveryStatus.DeliveryStatus] = Decoder.decodeEnumeration(DeliveryStatus)
  implicit val DeliveryStatusEncoder: Encoder[DeliveryStatus.DeliveryStatus] = Encoder.encodeEnumeration(DeliveryStatus)
  implicit val DeliveryStatusForUpdateDecoder: Decoder[DeliveryStatusForUpdate.DeliveryStatusForUpdate] = Decoder.decodeEnumeration(DeliveryStatusForUpdate)
  implicit val DeliveryStatusForUpdateEncoder: Encoder[DeliveryStatusForUpdate.DeliveryStatusForUpdate] = Encoder.encodeEnumeration(DeliveryStatusForUpdate)
  implicit val DiscountCardModeDecoder: Decoder[DiscountCardMode.DiscountCardMode] = Decoder.decodeEnumeration(DiscountCardMode)
  implicit val DiscountCardModeEncoder: Encoder[DiscountCardMode.DiscountCardMode] = Encoder.encodeEnumeration(DiscountCardMode)
  implicit val ErrorCodeDecoder: Decoder[ErrorCode.ErrorCode] = Decoder.decodeEnumeration(ErrorCode)
  implicit val ErrorCodeEncoder: Encoder[ErrorCode.ErrorCode] = Encoder.encodeEnumeration(ErrorCode)
  implicit val FontStyleDecoder: Decoder[FontStyle.FontStyle] = Decoder.decodeEnumeration(FontStyle)
  implicit val FontStyleEncoder: Encoder[FontStyle.FontStyle] = Encoder.encodeEnumeration(FontStyle)
  implicit val GenderDecoder: Decoder[Gender.Gender] = Decoder.decodeEnumeration(Gender)
  implicit val GenderEncoder: Encoder[Gender.Gender] = Encoder.encodeEnumeration(Gender)
  implicit val HousesRangeTypeDecoder: Decoder[HousesRangeType.HousesRangeType] = Decoder.decodeEnumeration(HousesRangeType)
  implicit val HousesRangeTypeEncoder: Encoder[HousesRangeType.HousesRangeType] = Encoder.encodeEnumeration(HousesRangeType)
  implicit val IikoCardSearchScopeDecoder: Decoder[IikoCardSearchScope.IikoCardSearchScope] = Decoder.decodeEnumeration(IikoCardSearchScope)
  implicit val IikoCardSearchScopeEncoder: Encoder[IikoCardSearchScope.IikoCardSearchScope] = Encoder.encodeEnumeration(IikoCardSearchScope)
  implicit val IikoNetUserSexDecoder: Decoder[IikoNetUserSex.IikoNetUserSex] = Decoder.decodeEnumeration(IikoNetUserSex)
  implicit val IikoNetUserSexEncoder: Encoder[IikoNetUserSex.IikoNetUserSex] = Encoder.encodeEnumeration(IikoNetUserSex)
  implicit val OperationCodeDecoder: Decoder[OperationCode.OperationCode] = Decoder.decodeEnumeration(OperationCode)
  implicit val OperationCodeEncoder: Encoder[OperationCode.OperationCode] = Encoder.encodeEnumeration(OperationCode)
  implicit val OrderItemStatusDecoder: Decoder[OrderItemStatus.OrderItemStatus] = Decoder.decodeEnumeration(OrderItemStatus)
  implicit val OrderItemStatusEncoder: Encoder[OrderItemStatus.OrderItemStatus] = Encoder.encodeEnumeration(OrderItemStatus)
  implicit val OrderItemTypeDecoder: Decoder[OrderItemType.OrderItemType] = Decoder.decodeEnumeration(OrderItemType)
  implicit val OrderItemTypeEncoder: Encoder[OrderItemType.OrderItemType] = Encoder.encodeEnumeration(OrderItemType)
  implicit val OrderServiceTypeDecoder: Decoder[OrderServiceType.OrderServiceType] = Decoder.decodeEnumeration(OrderServiceType)
  implicit val OrderServiceTypeEncoder: Encoder[OrderServiceType.OrderServiceType] = Encoder.encodeEnumeration(OrderServiceType)
  implicit val OrderSortPropertyDecoder: Decoder[OrderSortProperty.OrderSortProperty] = Decoder.decodeEnumeration(OrderSortProperty)
  implicit val OrderSortPropertyEncoder: Encoder[OrderSortProperty.OrderSortProperty] = Encoder.encodeEnumeration(OrderSortProperty)
  implicit val OrderStatusDecoder: Decoder[OrderStatus.OrderStatus] = Decoder.decodeEnumeration(OrderStatus)
  implicit val OrderStatusEncoder: Encoder[OrderStatus.OrderStatus] = Encoder.encodeEnumeration(OrderStatus)
  implicit val PaymentProcessingTypeDecoder: Decoder[PaymentProcessingType.PaymentProcessingType] = Decoder.decodeEnumeration(PaymentProcessingType)
  implicit val PaymentProcessingTypeEncoder: Encoder[PaymentProcessingType.PaymentProcessingType] = Encoder.encodeEnumeration(PaymentProcessingType)
  implicit val PaymentTypeKindDecoder: Decoder[PaymentTypeKind.PaymentTypeKind] = Decoder.decodeEnumeration(PaymentTypeKind)
  implicit val PaymentTypeKindEncoder: Encoder[PaymentTypeKind.PaymentTypeKind] = Encoder.encodeEnumeration(PaymentTypeKind)
  implicit val PersonalDataConsentStatusDecoder: Decoder[PersonalDataConsentStatus.PersonalDataConsentStatus] = Decoder.decodeEnumeration(PersonalDataConsentStatus)
  implicit val PersonalDataConsentStatusEncoder: Encoder[PersonalDataConsentStatus.PersonalDataConsentStatus] = Encoder.encodeEnumeration(PersonalDataConsentStatus)
  implicit val ProgramTypeDecoder: Decoder[ProgramType.ProgramType] = Decoder.decodeEnumeration(ProgramType)
  implicit val ProgramTypeEncoder: Encoder[ProgramType.ProgramType] = Encoder.encodeEnumeration(ProgramType)
  implicit val RefillTypeDecoder: Decoder[RefillType.RefillType] = Decoder.decodeEnumeration(RefillType)
  implicit val RefillTypeEncoder: Encoder[RefillType.RefillType] = Encoder.encodeEnumeration(RefillType)
  implicit val ReserveCancelReasonDecoder: Decoder[ReserveCancelReason.ReserveCancelReason] = Decoder.decodeEnumeration(ReserveCancelReason)
  implicit val ReserveCancelReasonEncoder: Encoder[ReserveCancelReason.ReserveCancelReason] = Encoder.encodeEnumeration(ReserveCancelReason)
  implicit val ReserveStatusDecoder: Decoder[ReserveStatus.ReserveStatus] = Decoder.decodeEnumeration(ReserveStatus)
  implicit val ReserveStatusEncoder: Encoder[ReserveStatus.ReserveStatus] = Encoder.encodeEnumeration(ReserveStatus)
  implicit val SortDirectionDecoder: Decoder[SortDirection.SortDirection] = Decoder.decodeEnumeration(SortDirection)
  implicit val SortDirectionEncoder: Encoder[SortDirection.SortDirection] = Encoder.encodeEnumeration(SortDirection)
  implicit val SplitOrderBetweenCashRegistersDecoder: Decoder[SplitOrderBetweenCashRegisters.SplitOrderBetweenCashRegisters] = Decoder.decodeEnumeration(SplitOrderBetweenCashRegisters)
  implicit val SplitOrderBetweenCashRegistersEncoder: Encoder[SplitOrderBetweenCashRegisters.SplitOrderBetweenCashRegisters] = Encoder.encodeEnumeration(SplitOrderBetweenCashRegisters)
  implicit val TemplateTypeDecoder: Decoder[TemplateType.TemplateType] = Decoder.decodeEnumeration(TemplateType)
  implicit val TemplateTypeEncoder: Encoder[TemplateType.TemplateType] = Encoder.encodeEnumeration(TemplateType)
  implicit val WebHookEventTypeDecoder: Decoder[WebHookEventType.WebHookEventType] = Decoder.decodeEnumeration(WebHookEventType)
  implicit val WebHookEventTypeEncoder: Encoder[WebHookEventType.WebHookEventType] = Encoder.encodeEnumeration(WebHookEventType)
}
