/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

  /**
   * Request to calculate loyalty operations for order.
   */
case class CalculateCheckinRequest(
  order: Order,
  /* Number of applied coupon. Can be null. */
  coupon: Option[String] = None,
  /* Referrer id. */
  referrerId: Option[UUID] = None,
  /* Identifier of a target terminal. Should be used only when auto distribution is off and no call center operator is available. */
  terminalGroupId: Option[UUID] = None,
  /* List of identifiers of applied campaigns. Should be empty if no payment method is used. */
  availablePaymentMarketingCampaignIds: Option[Seq[UUID]] = None,
  /* List of manually applied to order conditions. */
  applicableManualConditions: Option[Seq[UUID]] = None,
  /* Applicable manual discounts. */
  dynamicDiscounts: Option[Seq[DynamicDiscount]] = None,
  /* Loyalty trace is enabled. */
  isLoyaltyTraceEnabled: Option[Boolean] = None,
  /* Organization id. */
  organizationId: UUID
)

