/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

  /**
   * Request for cancel the order.
   */
case class CancelOrderRequest(
  /* Organization ID.                Can be obtained by `/api/1/organizations` operation. */
  organizationId: UUID,
  /* Order ID. */
  orderId: UUID,
  /* Fill this field with id of the new order if current order has been moved to the new RMS/terminal group. */
  movedOrderId: Option[UUID] = None,
  /* Cancel order dictionary item id.   > Allowed from version `7.7.1`. */
  cancelCauseId: Option[UUID] = None,
  /* Removal type (for delete printed order items).   > Allowed from version `7.7.1`. */
  removalTypeId: Option[UUID] = None,
  /* User for writeoff (for delete printed order items).   > Allowed from version `7.7.1`. */
  userIdForWriteoff: Option[UUID] = None
)

