/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

  /**
   * Combo in order.
   */
case class Combo(
  /* Combo ID.  MUST be unique for the whole system. Therefore it must be generated with Guid.NewGuid(). */
  id: UUID,
  /* Name of combo. */
  name: String,
  /* Quantity. */
  amount: Int,
  /* Price of one combo. */
  price: Double,
  /* Combo validity ID. */
  sourceId: UUID,
  /* Card program ID.   > Allowed from version `7.6.1`. */
  programId: Option[UUID] = None,
  /* Size ID. Required if combo has a size scale.   > Allowed from version `8.5.6`. */
  sizeId: Option[UUID] = None
)

