/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import ru.restomatik.client.model.OrderServiceType._

import java.util.UUID

  /**
   * Delivery order.
   */
case class DeliveryOrder(
  /* External menu ID. */
  menuId: Option[String] = None,
  /* Order ID. Must be unique.  > If sent null, it generates automatically on iikoTransport side. */
  id: Option[UUID] = None,
  /* Order external number.   > Allowed from version `8.0.6`. */
  externalNumber: Option[String] = None,
  /* Order fulfillment date.  > Date and time must be local for delivery terminal, without time zone (take a look at example).   > If null, order is urgent and time is calculated based on customer settings,  > i.e. the shortest delivery time possible.  > Permissible values: from current day and 60 days on. */
  completeBefore: Option[String] = None,
  /* Telephone number.  > Must begin with symbol \"+\" and must be at least 8 digits. */
  phone: String,
  /* Order type ID.     Can be obtained by `/api/1/deliveries/order_types` operation.    > Only one of the fields must be defined: **orderTypeId** or **orderServiceType**. */
  orderTypeId: Option[UUID] = None,
  orderServiceType: Option[OrderServiceType] = None,
  deliveryPoint: Option[IikoTransportPublicApiContractsDeliveriesRequestCreateOrderDeliveryOrderDeliveryPoint] = None,
  /* Order comment. */
  comment: Option[String] = None,
  customer: Option[IikoTransportPublicApiContractsDeliveriesRequestCreateOrderDeliveryOrderCustomer] = None,
  guests: Option[IikoTransportPublicApiContractsDeliveriesRequestCreateOrderDeliveryOrderGuests] = None,
  /* Marketing source (advertisement) ID.                 Can be obtained by `/api/1/marketing_sources` operation. */
  marketingSourceId: Option[UUID] = None,
  /* Operator ID.   > Allowed from version `7.6.3`. */
  operatorId: Option[UUID] = None,
  /* Order items. */
  items: Seq[OrderItem],
  /* Combos included in order. */
  combos: Option[Seq[Combo]] = None,
  /* Order payment components.   > Type **IikoCard** allowed from version `7.1.5`. */
  payments: Option[Seq[Payment]] = None,
  /* Order tips components. */
  tips: Option[Seq[TipsPayment]] = None,
  /* The string key (marker) of the source (partner - api user) that created the order. Needed to limit the visibility of orders for external integration. */
  sourceKey: Option[String] = None,
  discountsInfo: Option[IikoTransportPublicApiContractsDeliveriesRequestCreateOrderDeliveryOrderDiscountsInfo] = None,
  loyaltyInfo: Option[IikoTransportPublicApiContractsDeliveriesRequestCreateOrderDeliveryOrderLoyaltyInfo] = None,
  chequeAdditionalInfo: Option[IikoTransportPublicApiContractsDeliveriesRequestCreateOrderDeliveryOrderChequeAdditionalInfo] = None,
  /* Order external data.   > Allowed from version `8.0.6`. */
  externalData: Option[Seq[ExternalData]] = None
)

object DeliveryOrderEnums {

}
