/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import ru.restomatik.client.model.AddressFormatType._
import ru.restomatik.client.model.AddressHintsServiceType._
import ru.restomatik.client.model.DeliverySettingsServiceType._

import java.util.UUID

  /**
   * Organization details.
   */
case class ExtendedOrganizationInfo(
  /* Country. */
  country: String,
  /* Restaurant address. */
  restaurantAddress: String,
  /* Latitude. */
  latitude: Double,
  /* Longitude. */
  longitude: Double,
  /* Regional setting \"Use the UAE Addressing System\". */
  useUaeAddressingSystem: Boolean,
  /* iikoRMS version. */
  version: String,
  /* ISO currency code (for example: RUB, USD, EUR). */
  currencyIsoName: String,
  /* Value rounding of position. */
  currencyMinimumDenomination: Double,
  /* Country dialing code. */
  countryPhoneCode: String,
  /* Require mandatory marketing source input when creating a delivery. */
  marketingSourceRequiredInDelivery: Boolean,
  /* Default delivery city. */
  defaultDeliveryCityId: UUID,
  /* Delivery cities. */
  deliveryCityIds: Seq[UUID],
  deliveryServiceType: DeliverySettingsServiceType,
  /* Default payment type for CallCenter. */
  defaultCallCenterPaymentTypeId: UUID,
  /* Allow text comments for order items (in all restaurant sections). */
  orderItemCommentEnabled: Boolean,
  /* Restaurant`s INN (Taxpayer Identification Number). */
  inn: String,
  addressFormatType: AddressFormatType,
  /* Determines whether to use delivery confirmation. */
  isConfirmationEnabled: Boolean,
  /* Confirm orders time interval. */
  confirmAllowedIntervalInMinutes: Int,
  /* Determines whether organization is hosted in iikoCloud. */
  isCloud: Boolean,
  /* If the store allows orders for anonymous guests, then it is not necessary to transfer  information about the guest as part of the delivery order. You can only transfer  the phone number and optionally name of the guest, which will not be stored in the guest base  and will only be used for the delivery of a current delivery order. */
  isAnonymousGuestsAllowed: Option[Boolean] = None,
  /* Available address lookup services. */
  addressLookup: Seq[AddressHintsServiceType],
  responseType: String,
  /* Organization ID.                Can be obtained by `/api/1/organizations` operation. */
  id: UUID,
  /* Organization name. */
  name: String,
  /* Organization`s code. */
  code: Option[String] = None,
  /* Organization`s external data. */
  externalData: Option[Seq[ExternalData]] = None
)

object ExtendedOrganizationInfoEnums {

}
