/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import ru.restomatik.client.model.ReserveCancelReason._
import ru.restomatik.client.model.ReserveStatus._

import java.util.UUID

  /**
   * Banquet/reserve.
   */
case class IikoTransportPublicApiContractsReservesReserveInfoReserve(
  customer: Customer,
  /* Estimated guests count. */
  guestsCount: Int,
  /* Optional comment for reserve or banquet. */
  comment: Option[String] = None,
  /* Estimated banquet duration. */
  durationInMinutes: Long,
  /* Whether to remind staff to prepare table beforehand. */
  shouldRemind: Boolean,
  status: ReserveStatus,
  cancelReason: Option[ReserveCancelReason] = None,
  /* Reserved table IDs. */
  tableIds: Seq[UUID],
  /* Estimated time when reserve will be closed or banquet will be started. */
  estimatedStartTime: String,
  /* Time when guests came and reserve was closed or banquet was started. */
  guestsComingTime: Option[String] = None,
  /* Telephone number. */
  phone: Option[String] = None,
  /* Event type.   > Allowed from version `8.5.6`. */
  eventType: Option[String] = None,
  order: Option[IikoTransportPublicApiContractsReservesReserveOrder] = None
)

object IikoTransportPublicApiContractsReservesReserveInfoReserveEnums {

}
