/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import ru.restomatik.client.model.ProgramType._
import ru.restomatik.client.model.RefillType._
import ru.restomatik.client.model.TemplateType._

import java.util.UUID

  /**
   * Loyalty program.
   */
case class LoyaltyProgram(
  /* Program id. */
  id: Option[UUID] = None,
  /* Program name. Can be null. */
  name: Option[String] = None,
  /* Program description. Can be null. */
  description: Option[String] = None,
  /* Program works since date. */
  serviceFrom: Option[String] = None,
  /* Program works till date. */
  serviceTo: Option[String] = None,
  /* Notify customer when balance has changed (sms/push). */
  notifyAboutBalanceChanges: Option[Boolean] = None,
  programType: Option[ProgramType] = None,
  /* Program is active. */
  isActive: Option[Boolean] = None,
  /* Wallet id. Program has only wallet that means global payment type for customers. */
  walletId: Option[UUID] = None,
  /* Program marketing campaigns. */
  marketingCampaigns: Option[Seq[MarketingCampaignInfo]] = None,
  /* Program applied organizations. */
  appliedOrganizations: Option[Seq[UUID]] = None,
  templateType: Option[TemplateType] = None,
  /* Program has welcome bonus. */
  hasWelcomeBonus: Option[Boolean] = None,
  /* All new customers will get bonus. */
  welcomeBonusSum: Option[Double] = None,
  /* Exchange rate for bonuses and real currency. */
  isExchangeRateEnabled: Option[Boolean] = None,
  refillType: Option[RefillType] = None
)

object LoyaltyProgramEnums {

}
