/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

  /**
   * Marketing campaign info.
   */
case class MarketingCampaignInfo(
  /* Marketing campaign id. */
  id: Option[UUID] = None,
  /* Loyalty program id. */
  programId: Option[UUID] = None,
  /* Loyalty program name. Can be null. */
  name: Option[String] = None,
  /* Marketing campaign description. Can be null. */
  description: Option[String] = None,
  /* Marketing campaign is active. */
  isActive: Option[Boolean] = None,
  /* Marketing campaign works since date. */
  periodFrom: Option[String] = None,
  /* Marketing campaign works till date. Null means limitless. */
  periodTo: Option[String] = None,
  /* Conditions and actions that will be checked when order is processed. */
  orderActionConditionBindings: Option[Seq[MarketingCampaignActionConditionBindingInfo]] = None,
  /* Conditions and actions that will be checked by schedule. */
  periodicActionConditionBindings: Option[Seq[MarketingCampaignActionConditionBindingInfo]] = None,
  /* Conditions and actions that will be checked by overdraft. */
  overdraftActionConditionBindings: Option[Seq[MarketingCampaignActionConditionBindingInfo]] = None,
  /* Conditions and actions that will be checked by guest registration. */
  guestRegistrationActionConditionBindings: Option[Seq[MarketingCampaignActionConditionBindingInfo]] = None
)

