/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

  /**
   * Order item modifier.
   */
case class OrderItemModifier(
  product: Product,
  /* Quantity. */
  amount: Double,
  /* Whether quantity of modifier depends on quantity of item. */
  amountIndependentOfParentAmount: Boolean,
  productGroup: Option[IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemModifierProductGroup] = None,
  /* Price per item unit. Can be sent different from the price in RMS. */
  price: Double,
  /* Whether price is predefined. */
  pricePredefined: Boolean,
  /* Total amount per item including tax, discounts/surcharges. */
  resultSum: Double,
  deleted: Option[IikoTransportPublicApiContractsDeliveriesResponseOrderOrderItemModifierDeleted] = None,
  /* Unique identifier of the item in the order and for the whole system. */
  positionId: Option[UUID] = None,
  /* Default amount. */
  defaultAmount: Option[Int] = None,
  /* Hide modifier in UI if \"amount\" equals \"defaultAmount\". */
  hideIfDefaultAmount: Option[Boolean] = None,
  /* Tax rate. */
  taxPercent: Option[Double] = None
)

