/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

  /**
   * Request for a list of orders by phone number.
   */
case class OrdersByDeliveryDateAndPhoneRequest(
  /* Delivery order phone number. */
  phone: String,
  /* Order delivery date (Local for delivery terminal). Lower limit.                Order details are stored for 90 days. */
  deliveryDateFrom: Option[String] = None,
  /* Order delivery date (Local for delivery terminal). Upper limit. */
  deliveryDateTo: Option[String] = None,
  /* Organization ID for which an order search will be performed.                Can be obtained by `/api/1/organizations` operation. */
  organizationIds: Seq[UUID],
  /* Revision start number beginning from which (but not including) new/edited orders will be returned. */
  startRevision: Option[Long] = None,
  /* Source keys. */
  sourceKeys: Option[Seq[String]] = None,
  /* Maximum number of items returned.  <remarks>  If null, all items will be returned.  </remarks> */
  rowsCount: Option[Int] = None
)

