/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

  /**
   * DTO for outside transferring of external menu group details.
   */
case class ProductsGroupInfo(
  /* Links to images. */
  imageLinks: Seq[String],
  /* Parent group. */
  parentGroup: Option[UUID] = None,
  /* Group's order (priority) in menu. */
  order: Int,
  /* On-the-menu attribute. */
  isIncludedInMenu: Boolean,
  /* Is group modifier attribute.  * true - group modifier.  * false - external menu group. */
  isGroupModifier: Boolean,
  /* ID. */
  id: UUID,
  /* SKU. */
  code: Option[String] = None,
  /* Name. */
  name: String,
  /* Description. */
  description: Option[String] = None,
  /* Additional information. */
  additionalInfo: Option[String] = None,
  /* Tags. */
  tags: Option[Seq[String]] = None,
  /* Is-Deleted attribute. */
  isDeleted: Option[Boolean] = None,
  /* SEO description for client. */
  seoDescription: Option[String] = None,
  /* SEO text for robots. */
  seoText: Option[String] = None,
  /* SEO key words. */
  seoKeywords: Option[String] = None,
  /* SEO header. */
  seoTitle: Option[String] = None
)

