/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import ru.restomatik.client.model.OrderItemType._

import java.util.UUID

  /**
   * DTO for outside transferring of external menu item details.
   */
case class ProductInfo(
  /* Fat per 100g. */
  fatAmount: Option[Double] = None,
  /* Protein per 100g. */
  proteinsAmount: Option[Double] = None,
  /* Carbohydrate per 100g. */
  carbohydratesAmount: Option[Double] = None,
  /* Calories per 100g. */
  energyAmount: Option[Double] = None,
  /* Fat per item. */
  fatFullAmount: Option[Double] = None,
  /* Protein per item. */
  proteinsFullAmount: Option[Double] = None,
  /* Carbohydrate per item. */
  carbohydratesFullAmount: Option[Double] = None,
  /* Calories per item. */
  energyFullAmount: Option[Double] = None,
  /* Item weight. */
  weight: Option[Double] = None,
  /* Stock list group in RMS. */
  groupId: Option[UUID] = None,
  /* Product category in RMS. */
  productCategoryId: Option[UUID] = None,
  /* dish | good | modifier. */
  `type`: Option[String] = None,
  orderItemType: Option[OrderItemType] = None,
  /* Modifier schema's ID. */
  modifierSchemaId: Option[UUID] = None,
  /* Modifier schema's name. */
  modifierSchemaName: Option[String] = None,
  /* Is product splittable. */
  splittable: Boolean,
  /* Item's unit of measurement. */
  measureUnit: Option[String] = None,
  /* Prices. */
  sizePrices: Option[Seq[SizePrice]] = None,
  /* Modifiers. */
  modifiers: Option[Seq[SimpleModifierInfo]] = None,
  /* Modifier groups. */
  groupModifiers: Option[Seq[GroupModifierInfo]] = None,
  /* Links to images. */
  imageLinks: Option[Seq[String]] = None,
  /* Do not print on bill. */
  doNotPrintInCheque: Option[Boolean] = None,
  /* External menu group. */
  parentGroup: Option[UUID] = None,
  /* Product's order (priority) in menu. */
  order: Option[Int] = None,
  /* Full name in a foreign language. */
  fullNameEnglish: Option[String] = None,
  /* Weighed product. */
  useBalanceForSell: Boolean,
  /* Open price. */
  canSetOpenPrice: Boolean,
  /* Payment subject. */
  paymentSubject: Option[String] = None,
  /* ID. */
  id: UUID,
  /* SKU. */
  code: Option[String] = None,
  /* Name. */
  name: String,
  /* Description. */
  description: Option[String] = None,
  /* Additional information. */
  additionalInfo: Option[String] = None,
  /* Tags. */
  tags: Option[Seq[String]] = None,
  /* Is-Deleted attribute. */
  isDeleted: Option[Boolean] = None,
  /* SEO description for client. */
  seoDescription: Option[String] = None,
  /* SEO text for robots. */
  seoText: Option[String] = None,
  /* SEO key words. */
  seoKeywords: Option[String] = None,
  /* SEO header. */
  seoTitle: Option[String] = None
)

object ProductInfoEnums {

}
