/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model


  /**
   * Table layout.
   */
case class SectionSchema(
  /* Layout width in px. */
  width: Int,
  /* Layout height in px. */
  height: Int,
  /* Collection of restaurant section marks. */
  markElements: Seq[RestaurantSectionMark],
  /* Collection of restaurant section tables. */
  tableElements: Seq[RestaurantSectionTable],
  /* Collection of restaurant section rectangles. */
  rectangleElements: Seq[RestaurantSectionRectangle],
  /* Collection of restaurant section ellipses. */
  ellipseElements: Seq[RestaurantSectionEllipse],
  /* Last modified time. */
  revision: Long,
  /* Is schema deleted. */
  isDeleted: Boolean
)

