/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import ru.restomatik.client.model.Gender._

import java.util.UUID

case class TableOrderCustomer(
  /* Existing customer ID in RMS.   > If null - the phone number and name is searched in database, otherwise the new customer is created in RMS. */
  id: Option[UUID] = None,
  /* Name of customer.  > Required if \"id\" == null.  > Not required if \"id\" specified. */
  name: Option[String] = None,
  /* Last name. */
  surname: Option[String] = None,
  /* Comment. */
  comment: Option[String] = None,
  /* Date of birth. */
  birthdate: Option[String] = None,
  /* Email. */
  email: Option[String] = None,
  /* Whether customer receives order status notification messages. */
  shouldReceiveOrderStatusNotifications: Option[Boolean] = None,
  gender: Option[Gender] = None,
  /* Customer phone.  > Required if \"id\" == null.  > Not required if \"id\" specified. */
  phone: Option[String] = None
)

object TableOrderCustomerEnums {

}
