/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import java.util.UUID

case class TransportMenuCategoryDto(
  items: Option[Seq[TransportItemDto]] = None,
  /* ID of the category of the external menu */
  id: Option[UUID] = None,
  /* Category name of the external menu */
  name: Option[String] = None,
  /* Category description */
  description: Option[String] = None,
  /* Links to images */
  buttonImageUrl: Option[String] = None,
  headerImageUrl: Option[String] = None
)

