/**
 * iikoCloud API
 * <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.restomatik.client.model

import ru.restomatik.client.model.ActionOnValidationRejection._
import ru.restomatik.client.model.DeliveryGeocodeServiceType._
import ru.restomatik.client.model.DeliveryRestrictionsMode._

import java.util.UUID

  /**
   * Request for update of delivery restrictions.
   */
case class UpdateDeliveryRestrictionsRequest(
  /* Organization ID.                Can be obtained by `/api/1/organizations` operation. */
  organizationId: UUID,
  deliveryGeocodeServiceType: DeliveryGeocodeServiceType,
  /* Link to the map of delivery service regions. */
  deliveryRegionsMapUrl: String,
  /* General standard of delivery time. */
  defaultDeliveryDurationInMinutes: Long,
  /* Default pickup time. */
  defaultSelfServiceDurationInMinutes: Long,
  /* Indication that all delivery points in all delivery zones use common delivery time limits. */
  useSameDeliveryDuration: Boolean,
  /* Indication that all delivery points for all delivery zones use the total minimum order amount. */
  useSameMinSum: Boolean,
  /* Total minimum order amount. */
  defaultMinSum: Double,
  /* Indication that all delivery points in all zones use common time limits. */
  useSameWorkTimeInterval: Boolean,
  /* The beginning of the interval of the total work time for all points and delivery zones,   in minutes from the beginning of the day. */
  defaultFrom: Int,
  /* End of the total work time interval for all points and delivery zones,   in minutes from the beginning of the day. */
  defaultTo: Int,
  /* Indication that all delivery points in all zones use the same schedule for all days of the week. */
  useSameRestrictionsOnAllWeek: Boolean,
  /* Restrictions. */
  restrictions: Seq[DeliveryRestrictionItem],
  /* Delivery zones. */
  deliveryZones: Seq[DeliveryZone],
  /* Reject delivery if we could not geocode the address. */
  rejectOnGeocodingError: Boolean,
  /* Add shipping cost to order. */
  addDeliveryServiceCost: Boolean,
  /* Indication that the cost is the same for all points of delivery. */
  useSameDeliveryServiceProduct: Boolean,
  /* Link to \"delivery service payment\". */
  defaultDeliveryServiceProductId: UUID,
  /* Use external delivery distribution service. */
  useExternalAssignationService: Boolean,
  /* Indication whether or not to trust on the fronts the call center mapping restrictions from the call center  if the composition of the order has not changed since the last check. If true, then trust. */
  frontTrustsCallCenterCheck: Boolean,
  /* Address of external delivery distribution service. */
  externalAssignationServiceUrl: String,
  /* Require an exact geocoding address. */
  requireExactAddressForGeocoding: Boolean,
  zonesMode: DeliveryRestrictionsMode,
  /* Automatically assigned delivery method based on cartography. */
  autoAssignExternalDeliveries: Boolean,
  actionOnValidationRejection: ActionOnValidationRejection
)

object UpdateDeliveryRestrictionsRequestEnums {

}
